### ISSUE TITLE
Firestore (Firebase) as database

### ISSUE THREAD

**Issue by HausOfAlejandro** [agentejo/cockpit#1042]
I'm loving Cockpit! I was wondering if is there any chance to use it with Firestore as database service, or maybe, any tip on how can I create a controller to achieve this? :-)

**Comment by ronaldaug** [comment]
Why do you want to use Cockpit with Firestore?

I think It's better to use only one of them (Cockpit or Firestore). 

If you'll use with Cockpit, I guess the server responses will be slow because of multiple requests.
As Firestore has a data limit (2k requests per day), if you want more requests you have to pay firebase.

Cockpit is 100% free and you only need an apache hosting.

**Comment by HausOfAlejandro** [comment]
I just found Cockpit and I'm loving the CMS itself, but all my workflow (databases, cloud functions, storage, etc) are based on Firebase; the main reason is that I would like to use the Google Cloud infrastructure instead of my own because the responses times and costs.. :-)

**Comment by aheinze** [comment]
Sorry, no firebase support is planned.

**Comment by benwinding** [comment]
On the website it says MongoDB is supported, which has a very similar API. 

Also It's 20k requests that are free, not 2k.And after that, their pricing is amazingly cheap. Currently it's:

- $0.18 for 100k writes
- $0.06 for 100k reads

https://cloud.google.com/firestore/pricing

Is there anyway I could help implement a Firestore connector?
