### ISSUE TITLE
User management without admin rights

### ISSUE THREAD

**Issue by n84ck** [agentejo/cockpit#1432]
Hello, Is there a way to add/remove users without admin rights? Currently I can grant user handling premission to a specific group, but there is no "add account" button in the accounts page (without admin rights), so they only can edit the existing users.

**Comment by SamSmirnoy** [comment]
Hellow,

Unfortunately no, the "Add Account" button is only visible for `super admins`. You can still access the page directly on `/accounts/create`, and you can also create user accounts on this page, but since only super admins are able to choose a group each new created user will be automatically assigned to `Admin` (the default value), which is probably not what you want.

Reference:
- Add-Account Button: https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/views/accounts/index.php#L10
- Group Select Field: https://github.com/agentejo/cockpit/blob/next/modules/Cockpit/views/accounts/account.php#L161

~ Sam.

**Comment by n84ck** [comment]
Thank you!
