### ISSUE TITLE
[Forms] No option for Mailer Reply To

### ISSUE THREAD

**Issue by Hanawa02** [agentejo/cockpit#1453]
At the moment the only option taken from the Rest API to the Mailer from PHP is the subject, and adding the Reply To would be really nice.

The change is quite small (I was not able to create a PR for it myself, lacking permission for what It looks), the changes would be the following:

In the file `\modules\Forms\Controller\RestApi.php`, submit function, under the scope for adding the __mailsubject option, add the following code:

```php
            if ($this->param('__replyto')) {
                $options['reply_to'] = $this->param('__replyto');
            }
```
![image](https://user-images.githubusercontent.com/11237366/124742338-e5a7f480-df1c-11eb-826c-e7d4d243f3e0.png)

**Comment by MarcTabaries** [comment]
I take the liberty of posting a message here because I'm having a problem with the customization of the forms in Cockpit.

Indeed, I want to change the subject of the emails which is by default "New form data for: XXX". If I understood correctly, you have to use "__mailsubject" variable. I saw that your subject was different ... but I said to myself that you had undoubtedly succeeded in using this variable as you propose to extend the possibilities of Cockpit by offering new possibilities ("__replyto").

The problem is, I don't see where to put this variable. It would seem that it's necessary to indicate it directly in the form via a hidden field ... but since I'm using Cockpit + React JS and not PHP it doesn't work (no access to : $_REQUEST, $_POST, ...).

Can you tell me where you put this "__mailsubject" variable ?

If you are ever interested, here is a link to my problem : https://github.com/agentejo/cockpit/issues/1456

In advance, thank you for your return.

**Comment by Hanawa02** [comment]
@MarcTabaries you need to add it as a parameter, so it would be `forms/yourForm?__mailSubject=YourSubject`. You may need to encode the subject, but aside from that, should be straightforward.

**Comment by MarcTabaries** [comment]
Thanks to you and [MarcoDaniels](https://github.com/agentejo/cockpit/issues/1456#issuecomment-878529507), I realized that we had to put "__mailsubject" directly at the level of the URI. Indeed, it was not very complicated. The official documentation was not clear enough at this level.

Your idea to do the same thing with "__replyto" would be really cool !

In any case, thank you for your help.

**Comment by Hanawa02** [comment]
Yes, the documentation, unfortunately, is lacking a lot, I suggest you always take a look at the [forum](https://discourse.getcockpit.com/), I always look there when I need to see something about the cockpit.

**Comment by abernh** [comment]
Adding a `reply_to` to the `$options` can already be done by hooking into the `forms.submit.before` event.

https://github.com/agentejo/cockpit/blob/568b0124352f6d27df359e8c19a70d2dd1961e87/modules/Forms/bootstrap.php#L285

**Comment by Hanawa02** [comment]
@abernh we are using a docker image based on the current repository of Cockpit, so we don't change the system at all, and we would prefer to continue just using it like this.

**Comment by aheinze** [comment]
see my comment here: https://github.com/agentejo/cockpit/pull/1455#issuecomment-908394598
