### ISSUE TITLE
Question: Can you use cockpit.js from another url?

### ISSUE THREAD

**Issue by thond1st** [agentejo/cockpit#420]
Hi,

I have setup cockpit on my domain "example.com".
I was trying to use it from my local machine but I am getting :

> ReferenceError: Cockpit is not defined

I added this to my html in the head section:
`<script type="text/javascript" src="http://example.com/cockpit/rest/api-js?token=..........................."></script>`

Is it possible to use cockpit.js this way or your site or app should be in the same url?

Thanks,
Anthony

**Comment by metawort** [comment]
I think you're code should work. The problem might be, that you actually have to include the script via this URL: `http://example.com/cockpit/index.php/rest/api-js?token=...`, although the documentation says otherwise.

Either the documentation needs to be corrected or the implementation of the API. I'd prefer the latter.
