### ISSUE TITLE
How to get _id of the item saved?

### ISSUE THREAD

**Issue by utamir** [agentejo/cockpit#433]
```
$idx = cockpit('collections')->save_entry('posts',[ 
                            "data"=> $entry
                            ]);
```

return some id by which is it not possible to search (db sequence). Technically it is possible to sort and get latest, but it is not really robust solution. Also the original reference entry is not being updated.

**Comment by aheinze** [comment]
after saving you'll get a field ``_id`` attached which is the unique id of the item

```
cockpit('collections')->save_entry('posts', $entry);

echo $entry['_id'];
```

**Comment by utamir** [comment]
i tried that. Not really works...

`echo "before";
print_r($entry);
$kid = cockpit('collections')->save_entry('posts', $entry);
echo "after ".$kid;
print_r($entry);`

> beforeArray
> (
>     [title] => Test title
>     [content] => Test content
> )
> after 682Array
> (
>     [title] => Test title
>     [content] => Test content
> )

**Comment by webcliq** [comment]
Utamir, in the text of your opening request, you asked how to return the "id" of the record which has been affected by the update or insert and Artur gave you the correct answer that the numeric id (or in the case of Cockpit _id) is returned by the method. Thus a successful save returns "628", exactly what one would expect.

If this answer is not what you were expecting or does not answer your question, then I have to say that you did not explain yourself very well in your initial request. I appreciate that both of you are using English as a second language but that is the way of the IT world in which we live.

If I can help in any way to make sense of what you are trying to achieve so that Artur (or someone else) can give you a more fulsome and appropriate answer, please respond.

If it is a matter of training and comprehension of Cockpit it would probably be better that you asked your question in the Google Cockpit Group rather than raise an issue on Github.

**Comment by utamir** [comment]
Thank you, @webcliq 
628 is sequence id coming from db. Cockpit has no interface to handle this id (at least externally). The only usable id is _id. and i would expect Cockpit to work the way @aheinze told (also this is the interface for data store  internally. But this not happens, $entry is transferred by value, not reference
