### ISSUE TITLE
question on the CMS to use with multi platform publishing

### ISSUE THREAD

**Issue by istvano** [agentejo/cockpit#509]
Hi,

We are planing to move some offline publishing to online and I am wondering if cockpit could help with this.

We have "reference book" style technical information document.  The information is intended to be found quickly when needed. 
Reference works are usually referred to for particular pieces of information, rather than read beginning to end.
This book is intended to be consulted for information on specific matters.

The source of the current book exists as Word and InDesign document.
Currently it is distributed as a ePub but it can be printed as needed.

We would like to convert this offering to the following:

- the book's content needs to be in a content repository where content is disconnected from it's format
- the content needs to be very easily editable using a GUI
- the content will be tagged and categorized by the editors
- the content needs to be versioned with the possiblity to track who changed what
- possibility to do multi format publishing ( Microsoft Word, PDF, Website, Mobile app, ePub) - pluggable output
- very robust search function ( Elasticsearch or SOLR or similar )
- replace the images with Videos and be able to output still images for the PDF and Streaming Video for on-line or mobile publicatinos
- the ability to read the data via APIs 
- perhaps export it to XML to be further processed etc.

Do you think I could use cockpit with this successfully ? Any advise, idea are most appreciated.

Thanks

**Comment by gryphonmyers** [comment]
Cockpit would be able to tick a lot of these boxes. It's basically a GUI into a MongoDB database. You can build your database schemae right in Cockpit, then access them over a REST API (supporting most MongoDB operators, so you can filter, sort and paginate the output to suit a wide variety of needs). It sounds like some of your needs (image / video replacement, outputting to XML rather than JSON, converting to word, PDF, etc) might necessitate another layer consuming and processing the JSON from the REST API.

**Comment by gryphonmyers** [comment]
One thing Cockpit does not currently do (AFAIK) is data revisions.
