### ISSUE TITLE
Bug: Image display from assets in Layout field broken

### ISSUE THREAD

**Issue by ling1726** [agentejo/cockpit#568]
Hello,

When adding images to a layout field. If the image is selected from assets, then the preview will not display because the url is malformed. However, selecting an image directly from the right folder under the 'select image' option will have a well formed preview url.

The preview url from an image from assets will have a missing domain name:
http://storage/..... instead of http://domain.com/storage/....

**Comment by cocoanton** [comment]
I have also struck upon this problem. If we make the asset-manager strip out the leading / everything works as expected.
So [here in field-image.tag](https://github.com/agentejo/cockpit/blob/2b310802321ef9233a749f328f1a748546c99bd5/modules/Cockpit/assets/components/field-image.tag#L113) it should read 
```$this.image.path = ASSETS_URL.replace(SITE_URL+'/', '')+assets[0].path;```

I'm not really getting the whole riot-thing, otherwise I could do a pull-request
