### ISSUE TITLE
[NEXT] How to load cockpit api to the templates

### ISSUE THREAD

**Issue by antonlukin** [agentejo/cockpit#575]
I've try to find how to make simple blog as described in this tutorial: https://github.com/COCOPi/cockpit-docs/blob/master/tutorials/simple_blog.md

All old functions are not working in NEXT cockpit. So I can't understand how to use collections/regions/forms in my project.

**Comment by raffaelj** [comment]
Since I came here to find a solution and this issue is still open... - After reading the code and some try-and-error, I got it. The syntax changed a bit. There is no function `collections` anymore. You have to give the module name `collections` and you have to pass an object with options into the function `cockpit` for filtering.

My cockpit is not in the same directory, so you have to change the path in line 4 to your needs. `.htaccess`, `views/index.php` and `views/article.php` are the same like in the example. My collection's name is "pages". Change the name in both functions (`find` and `findOne`), too.

By and by I understand this nice looking, but poorly documented CMS...

Content of `index.php`:

```php
<?php

//include cockpit
include_once('../cockpit/bootstrap.php');

$app = new Lime\App();

// bind routes

$app->bind("/", function() use($app) {

    $options = [
      "filter" => [
        "published" => true
      ]
    ];
    $posts = cockpit('collections')->find('pages', $options);

    return $app->render('views/index.php', ['posts' => $posts]);
});


$app->bind("/article/:id", function($params) use($app) {

    $post = cockpit('collections')->findOne('pages', ["_id"=>$params['id']]);

    return $app->render('views/article.php', ['post' => $post]);
});

$app->run();
```

**Comment by aheinze** [comment]
@raffaelj Cockpit is open source so please feel invited to contribute: https://github.com/agentejo/cockpit-docs

**Comment by raffaelj** [comment]
@aheinze OK. I start a new thread, because I need some clarification about the structure etc.

I think, this issue can be closed, since it's 9 months old and now it has an answer for people, who search for it the next time.
