### ISSUE TITLE
[Proposal] Add simple analytics

### ISSUE THREAD

**Issue by Escapado** [agentejo/cockpit#644]
Hey!

First of all I am a big fan of cockpit and I look forward to every release. It fits my needs perfectly and has become my goto solutions for a lot of things. However one thing that I would like to see would be the addition of a simple analytics functionality. As in: How many people clicked on this collection item today/last month/ever? How often was this region requested today/last month/ever? Maybe total unique IPs that requested anything today/last month/ever.

Would you guys think cockpit would benefit from this? I'd be especially interested in @aheinze opinion.

**Comment by tomdupont** [comment]
I also would like simple statistics. But in my opinion it should be made as a add-on, as it's not a core functionality.

I happen to be busy with making such a add-on. Currently it's only a widget with a chart of the rest api get calls. Will set up the repo this weekend.

![screen shot 2018-01-17 at 08 28 19](https://user-images.githubusercontent.com/15290357/35030738-6c993304-fb60-11e7-8294-b459c293b89f.png)

**Comment by aheinze** [comment]
@tomdupont great! I would also see this as an add-on module. excited what you'll come up with!

**Comment by Escapado** [comment]
Nice! Looking forward to that! 😀

**Comment by tomdupont** [comment]
Hi Guys!

First of all excuses me for being late. Because "statistics" is so broad and offers a wide spectrum of how users use it. I didn't find a ideal solution that would be performant/useful and also work for both MongoDB and SQLite.

However I think I found a pretty solid way using Google analytics.

Event tracking with [Google Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/)
Reporting with [Analytics Embed API](https://developers.google.com/analytics/devguides/reporting/embed/v1/)

The add-on would consist of:

- A page in cockpit settings to insert analytics id, optional settings , and select widgets for on the dashboard page
- Widgets for the cockpit dashboard

I would bind analytics events on event triggers (like collections.find.before.name) similar to how webhooks currently work, making a broad choice of use cases possible.

Any input on this?

**Comment by aheinze** [comment]
@tomdupont  I think you're looking into the right direction. If you allow, I would also suggest to add support for Piwik (https://matomo.org) as it is one of the leading and widely used Open Source analytics tool. I'm excited to see what you'll come up with 👍🏻
