### ISSUE TITLE
Security: howto protect login panel?

### ISSUE THREAD

**Issue by giauna** [agentejo/cockpit#654]
Is it possibile to set a custom URL to access to login panel ?

Expected behavior:
http://my-domain/data --> error 404
http://my-domain/my-custom-link --> login panel

Or, if you have other solutions to better protect an "easy to find" (*) access panel based on simple "admin-pass"...
(*) easy to find because "http://my-domain/data" is the same path used to call API...

Thank you!
(I love Cockpit!)

**Comment by pauloamgomes** [comment]
Hi @giauna , I had a similar requirement and did the following:

Configured nginx using proxy functionality to separate access to api and admin interface, main idea is to have admin interface in a specific subdomain and the api (that needs to be public accessible) in a different subdomain (e.g. api.domain.com) and denying access to /auth

```

# admin access
server {
    listen 80;
    server_name admin123456.mydomain.com; # set a subdomain that only you know

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# public access to api
server {
    listen 80;
    server_name api.mydomain.com;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # access uploads, images
    location /storage/ {
        expires 30d;
        log_not_found off;
        proxy_pass http://127.0.0.1:8001/storage/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # deny any access to admin interface
    location /auth {
      deny all;
    }
}

# Cockpit backend
server {
    server_name  default;
    listen       127.0.0.1:8001;

    root /var/www/html;

    # default nginx configurations for server here
}
```

So that way my application/website contacts with api.mydomain.com for retrieving collections, etc.. and I can access the admin interface on other url
This is a very simple scenario, as I recommend to have https and other configuration rules that are not implemented above
