### ISSUE TITLE
Separate Users / Sites

### ISSUE THREAD

**Issue by aidanayala** [agentejo/cockpit#673]
I'm looking at headless CMS platforms which have the ability to have separate sites with different users without needing a new installation of cockpit. Similar to how contentfull has "Spaces"

Can cockpit be configured to account for this?

**Comment by gryphonmyers** [comment]
Considering that cockpit takes a php file for its config, there shouldn't be anything stopping you from swapping in a different db name depending on the route you come in on. This would give you a completely different data set with the same codebase. For example:

```php
<?php
return [
    "database"    => [
        "server"  => "mongodb://localhost:27017",
        "options" => $_SERVER['REQUEST_URI'] === 'site-a') ? ["db" => "cockpitdb-a"] :  ["db" => "cockpitdb-b"]
    ]
];
?>

```

I have not tested this so not 100% sure this exact code will work out of the box

**Comment by aidanayala** [comment]
@gryphonmyers this is a nice solution for selecting the database. Thanks.

The next thing I'll need to tackle however is the user side of things.

I'd want them to be able to switch between "Sites" based on the ones they have access too.

Ideally we'd have this as a navbar drop down - showing the sites they are attributed too - click a site will load the relevant site in cockpit.

Can we customise the navbar safely?

**Comment by gryphonmyers** [comment]
Hm that is more complicated because now it sounds like you do want to share users between instances. Users are stored in the database like everything else, so using my suggestion, you'd actually have completely different user bases for the different "sites."

Based on what you're describing now, I'd question whether you actually need a separate "site." Cockpit is headless and is really just a place to organize and store data. A single instance of Cockpit can drive any number of "sites" via the REST API. You already have the ability to give collection-level permissions based on user group, so why not make your "sites" collections or groups of collections, and give access as needed based on user group?
