### ISSUE TITLE
Universal search engine :)

### ISSUE THREAD

**Issue by crealx** [agentejo/cockpit#705]
Hello !
I'm trying to do an universal search (search engine) in Cockpit.
First, I tried to use regexp :
<?php foreach(collection("post")->find(array('title'=> array('$regex' => $_POST['title'])))->sort(["created"=>"-1"]) as $item): ?>

Here, I can find post like in sql : 
`select * from post where title like '%$_POST['title']%';`

Now, I want to do it case insensive : something like : 
`select * from post where title like '%$_POST['title']%';`

But I failed :( I tried to use regexp for mongo... but it doesn't work.
Can you help me ?

THank you

**Comment by crealx** [comment]
You would have read :
`select * from post where lower(title) like '%lower($_POST['title'])%';`

**Comment by pauloamgomes** [comment]
I would approach a search functionality by leveraging a search engine like Apache Solr or Algolia. The contents can be indexed by pushing the contents to the search engine during a "collections.save.after" event.
Resuming I see some space for a custom addon that provides the mechanisms to integrate with such engines.

**Comment by pauloamgomes** [comment]
Exactly :)

**Comment by crealx** [comment]
Thank you ! I will have a look to this addon. Don't understant how it's work at first sight, but I will dig !

**Comment by cschweda** [comment]
The other approach is to go outside the API entirely and generate the search engine from whatever site is consuming the API. I've got a proof-of-concept project with Algolia here:

https://github.com/ICJIA/algolia-site-indexer

Essentially, this takes a sitemap.xml file for a site (in my case generated with Nuxt.js), parses it, and then one-by-one indexes each url from the site. If it's in the sitemap, it'll get indexed.

I grab key meta items -- title, keywords, description -- and then append a set limit of characters from the URL's main body (by checking whatever class/id attribute is used for the body content). I generate a unique Algolia objectID based on an MD5 hash of the actual URL. That way, I know the objectIDs are unique to each page.

Then I send all the results to the Algolia index.

Finally, I check and see if pages have been deleted since the last indexing. If so, I delete those pages from the Algolia index. (Added pages are automatically included, so I don't need to worry about those.)

In my actual site, I use the Algolia 'vue-instantsearch' tag to display the results. 

It works incredibly well. I'm not sure if this is the best way to do it, but for a basic, instant search. this works great!
