### ISSUE TITLE
Problem accessing entries with custom addon

### ISSUE THREAD

**Issue by muoto** [agentejo/cockpit#734]
I am writing a custom addon and would like to display the entires ("bookmarks") from a collection inside of my desktop widget but having difficulty doing so.  My code (which doesn't work) is below. Any ideas?

```
// Add Dashboard Widget
	$app->on('admin.init', function() {

        // dashboard widgets
        $this->on("admin.dashboard.widgets", function($widgets) {
            // NOTE: THIS CALL DOES NOT WORK, I CAN GET COLLECTIONS BUT NOT ENTRIES
            $bookmarks = $this->module('collections')->collections(true)->find("bookmarks");
            $widgets[] = [
                "name"    => "bookmarks",
                "content" => $this->view("bookmarks:views/widgets/dashboard.php", compact('bookmarks')),
                "area"    => 'aside-left'
            ];
        }, 100);
    });
```

**Comment by raffaelj** [comment]
try
`$bookmarks = $this->module('collections')->find("bookmarks");`
instead of
`$bookmarks = $this->module('collections')->collections(true)->find("bookmarks");`

or if it doesn't work, try `$bookmarks = $this->app->module('collections')->find("bookmarks");`

`->collections()` returns the schemas (+count) and not the entries.
`->find($collectionname)` returns fields

Another thing...
```php
$app->on('admin.init', function() {
    $bookmarks = $this->app->module('collections')->find('bookmarks');
    return $bookmarks;
}
```
works the same like
```php
$app->on('admin.init', function() use($app) {
    $bookmarks = $app->module('collections')->find('bookmarks');
    return $bookmarks;
}
```
