### ISSUE TITLE
Extending Cockpit

### ISSUE THREAD

**Issue by ThiagoMiranda** [agentejo/cockpit#740]
Hi.. First of all thanks for the great CMS.

I was wondering if I can make an alternative to read/write files instead of using the sqlite or mongo. Is there a pattern to do that? In my case I'm using the GatsbyJS and I'll try to save the data in .md files.

Thanks

**Comment by mpartipilo** [comment]
You don't need to store the .md files per se, you can just use a collection or a singleton with a markdown field to store the markdown.

**Comment by ThiagoMiranda** [comment]
@mpartipilo What I was trying to achieve is:
1- Hot reload from GatsbyJS ( saving a collection/post in cockpit, or any "external cms", does not fire it )
2- I can edit the Markdown via both ways in a text editor or cockpit.

**Comment by internetstyle** [comment]
Same issue. I would like to do the same thing. You did it?

**Comment by raffaelj** [comment]
I would love that feature, too and there are a few things out there in this direction.

@aheinze wrote [Copilot](https://github.com/agentejo/copilot). It's a flat file CMS on top of Cockpit. But Copilot uses it's own logic instead of the collections and it's not licensed for free use. I tried it a while ago and if I remember correctly, the markdown files are rendered on the fly without touching any database.

@zontarian wrote the [Hugo Cockpit addon](https://github.com/iakta/hugocockpit). It's not very flexible and you have to login and click to rebuild the Hugo site again and again.

I wrote a simple custom api endpoint (work in progress...) to provide collection data as markdown file to be reused with jekyll [here](https://github.com/raffaelj/cockpit-scripts/blob/master/custom-api-endpoints/jekyll.php).

One direction could be achieved relatively easy. After saving a collection, fire an event to store the content in a .md file, too. Something like:

```php
$app->on("collections.save.after", function($name, &$entry, $isUpdate) use ($app) {
    
    // get file naming schema (title, date etc.)
    
    // get frontmatter schema (yaml, toml etc.)
    
    // get content schema (title as headline, content etc.)
    
    // write the file to /cockpit/static/$name/2018-08-23-page-title.md
    // ...
    
});
```

The next problem would be to detect changes in the text files. If I don't want to run a service, that watches file changes permanently, I would add a webhook to update the changed files in a git repo after saving a collection in cockpit.

A git post hook could trigger a script, that updates Cockpit through the API after pushing changed text files to the git repo.

This way I would have my collections and a git repository with static files in sync.

It's not on my priority list, but if someone finds a clean solution, I'm interested in hearing about it or to do some tests and provide some help.
