### ISSUE TITLE
Following requirement(s) failed: PDO extension loaded with Sqlite support

### ISSUE THREAD

**Issue by ranjit-redekar** [agentejo/cockpit#767]
I have installed SQLite ( sudo apt-get install php-sqlite3). and after that restarted the apache2 service (sudo service apache2 restart). still facing this issue when trying to install cockpit.

configuration 
OS - Ubuntu 18.04
SQLite -  v 3.22.0
PHP - 7.1
..

**Comment by georgesamy** [comment]
I ran into the same issue, turns out the php that my apache2 service was using is different from the one I was installing sqlite3 to. Make a basic php script that calls `phpinfo();`  and open it from the browser. Then check which version of php is apache2 using, in my case I had to run `sudo apt-get install php5.6-sqlite3`
