### ISSUE TITLE
Set with multiple (or inline collectionlink)

### ISSUE THREAD

**Issue by basvdheijden** [agentejo/cockpit#790]
Is it possible to have a Set (a group of fields) multiple times on one entry? What I'm trying to achieve is having a "Recipe" collection with a Set called "Ingredients" and then having fields: "Substance" and "Quantity". But I want multiple ingredients in the recipe, each with its own substance and quantity fields.

I could achieve the above with collectionlinks and split out the Ingredients to a new collection. However, then I need to (first) define all the ingredients separately and then "link" them to the recipe. I don't want that. I want to be able to define the ingredients inline at the Recipe entry, because they won't be shared.

Thanks in advance for your help!

**Comment by basvdheijden** [comment]
I've searched through the code extensively, but I think it's not possible currently. if I want to build this into cockpit, where to start? What I'm thinking now is extending the "Set" field type to allow multiple occurences of the same Set on an entry. But I don't know how everything works on the storage level.

**Comment by gryphonmyers** [comment]
Yes you're encountering a problem I frequently run into when trying to model data with Cockpit. Generally I find it's better to put models in their own collections rather than sets / repeaters, but then you have this crappy data entry process as you've described. It would be so nice if the collection link field had an inline entry editor into the linked collection... no idea how difficult that would be to implement.

**Comment by basvdheijden** [comment]
I've solved it already with a combination of repeaters and set elements. So a repeater can contain a set and that one can then contain a repeater so you can nest all kinds of stuff.

**Comment by gryphonmyers** [comment]
Yes, though unfortunately localization process is pretty poor on any structures modeled in this way. You cannot have a deeply nested field localize independently on the root field. It's something I've wanted for a long time but it doesn't seem Artur is willing to add. If localization isn't an issue for you then it's probably fine the way you're doing it, but I think for projects where localization is essential, the inline collection entry editor would be much better.

**Comment by aheinze** [comment]
@basvdheijden sorry to hear that, but the devil is always in the detail. Cockpit will never try to support any possible data model out there. If it gets too specific I would always recommend to write a custom addon. My goal is always to keep everyday problems as simple as possible but provide enough flexibility to build custom solutions on top of Cockpit.

Regarding your statements about Cockpits code base I would like challenge them 😌 

What makes you think that the code is "old"? Yes, I took another approach. Instead of using popular frameworks like symfony and laravel for example, I built my own. But I always try to use and update Cockpits code base to make use of the latest php language improvements (Cockpit requires PHP >= 7) etc. That way I have full control over performance etc. Complicated? This is relative, I find it quite straightforward and easy to understand 🙈

And no composer is used? Well: https://github.com/agentejo/cockpit/blob/next/composer.json

I don't want to start to argue here. Everybody has always their own opinion and I'm the last one who wants to convince anyone of my opinion.

However, I hope you can find joy using Cockpit someday again! 

Btw, I'm always open for discussions and improvements✌️

Greets,
Artur
