### ISSUE TITLE
Memory size when using 'populate': 1

### ISSUE THREAD

**Issue by RoelantStegmann** [agentejo/cockpit#892]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) 

I have a catalog of products, and wanted to relate some products to other products ('brothers and sisters'). This is easily done, but now I wanted to show a small picture of these related products on my product page.  However, when I use `populate: 1` this results in the above memory error. A single product is like ~7000 characters. 

After some analysis, it seems that it works fine until product A -> B and B -> A. Although I only use populate: 1, this seems to raise the memory error.

**Comment by gryphonmyers** [comment]
You just need to bump the memory limit in your php.ini

**Comment by RoelantStegmann** [comment]
I would expect something else to work, since it works fine until product A is related to B and B is related to A?

**Comment by gryphonmyers** [comment]
It sounds like you created a circular dependency, which can cause populated
collection links to spiral out of control (usually when I encounter
problems like this it is a sign I need to rethink my design). It does sound
like it is continuing to populate beyond 1 recursion depth so maybe there
is some weird edge case. What is the exact structure

**Comment by RoelantStegmann** [comment]
Uhm its quite a big structure of a product. Would you want to see all? 

Product:
  name:
  ... 
  related_link_1
  related_link_2 
  related_link_3

And then we have some cases where product A has related_link_1 for product B and B contains the link vice versa.

**Comment by gryphonmyers** [comment]
OK so I think I understand what's going on. You have two items directly
linking each other, so even a populate depth of 1 is causing a recursion
loop that will never end. Since they are directly linking each other, each
populate operation is only 1 level deep, but infinite populate operations
are generated.

There should probably be a check for cases like this somewhere, but I also
think this is poor database design. I'd rethink the structure. Maybe some
ideas here:
https://www.codeproject.com/Articles/38655/Prevent-Circular-References-in-Database-Design
