### ISSUE TITLE
Creating language file - where's default?

### ISSUE THREAD

**Issue by DavidB137** [agentejo/cockpit#919]
Hi.

I'm creating a language file by changing values in this one: https://raw.githubusercontent.com/COCOPi/cockpit-i18n/master/cs.php, but I've found out that not every phrase is there, e.g. I cannot translate Singletons. So I've been searching for the default file, where is every phrase in English, so I can work with that one, but I couldn't find it. So where is it? Or can I get a file (like Czech one above) with every current phase identifier in it?

Thank you.

Dávid

**Comment by raffaelj** [comment]
> call in the terminal `./cp create-lang --lang fr --language French`
> This will create a language file in `/config/cockpit/i18n/fr.php` with all available language strings in your cockpit installation.

[source](https://discourse.getcockpit.com/t/edit-language-from-dashboard/228/9)

If you already translated strings, make a backup of your language file, keep it in the i18n dir and call the command above. The old translated strings will be appended.

I did it this way and translated a file from the COCOPI repo before. Afterwards I had 500+ strings instead of 300+ i18n strings. Use [this script](https://github.com/raffaelj/cockpit-scripts/blob/master/cli/create-lang.php) instead, if you want to keep existing translations, but remove unused strings.

**Comment by DavidB137** [comment]
Worked, thank you very much 👍
