### ISSUE TITLE
[Help]Filtering by Collectionlink field and filtering by locale

### ISSUE THREAD

**Issue by alverena** [agentejo/cockpit#925]
1. I checked the issue #681 which is marked as closed. Same with issue #631.
However, I don't see that the questions brought up there were fully answered. 

I'm using MongoDB version 4.0.3. 

 I have collection 'books' and a Collectionlink field 'series' in it. I want to filter books by the _id of the series. 

I've tried to add a filter:
`http://<host>/api/collections/get/books?token=923f7edcc84699c178be46b7e704c7&filter[series][_id]=5bea9e20b761bb18e70a2662`

But it doesn't work. 

2. I have 3 languages for content. I've tried to filter by `&lang='fr'` but I still have 3 values for each localized field in the response.  

For both points, please advise whether such filtering is possible at all? And if yes, how to do it.

**Comment by gryphonmyers** [comment]
1) You need to use the $elemMatch operator:

`http://<host>/api/collections/get/books?token=923f7edcc84699c178be46b7e704c7&filter[series][$elemMatch][_id]=5bea9e20b761bb18e70a2662`

2) are you sure 'fr' one of the languages set up in your config file? Also I've noticed the localization feature can leave unitialized (null) values sitting around, but they go away once a value is entered.

**Comment by alverena** [comment]
Thank you, it worked! 
Also, I have a freshly installed cockpit version with languages defined in the settings from the very start, and language filter works now too.

**Comment by bassauer-storms-media** [comment]
btw its important to note that this only works if your collection link is NOT multiple. As soon as its multiple cockpit stores the links as array which is not filterable at the moment

**Comment by gryphonmyers** [comment]
Unless I'm misunderstanding you, I don't think that's true. I have not had problems querying for objects with multiple collection links.

**Comment by bassauer-storms-media** [comment]
So assume I am calling this query:

`http://<host>/api/collections/get/jobs?token=xyz&filter[cats][$elemMatch][_id]=<the category id of which I want to have assigned jobs collection entries>`

while I have a collection called "jobs" (which is queried in the example above) which has a *multiple* collection link with the name "cats" that connects a collection called "job_categories" (which has only one single field called "name" (for the cat name) of the type text).

That approach does only work for me when the "cats" (collection link) field of the jobs collection is multiple:false.

As soon as I make it multiple:true (and of course then re-save the entries (otherwise they will stay unchanged even if the collection structure definition changed)) the API response will always be:

```
{
"error": true,
"message": "Oooops, something went wrong."
}
```

**Comment by gryphonmyers** [comment]
Interesting. That query gives me no problems. Are you using mongodb or
sqlite? If mongo (that is what I am using), make sure your mongodb driver
is up to date. Also make sure you are on PHP 7. If you are able to dig
through your server logs it may give you a clue what is failing.

**Comment by serjoscha87** [comment]
Well you named it - you are using mongodb. I am not. I am using SQLite though MongoLite (which is shipped with cockpit).

Thats why its not working.

Here is the proof:

https://github.com/agentejo/cockpit/issues/681#issuecomment-368273914

> Hi,
> 
> if you're using mongodb as cockpits data source ...................
> 
> but if you're using the default MongoLite data source then querying nested values isn't supported, sorry.

**Comment by gryphonmyers** [comment]
Ahh good to know. Sounds like you should switch to mongodb ;)
